environment:
  matrix:
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#       VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat
#       VCVARS_ARG:
#       ENABLE_UI: ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
      VCVARS_ARG:
      ENABLE_UI: ON

install:
  - call "%VCVARS_FILE%" %VCVARS_ARG%

before_build:
  - git submodule update --init --recursive
  
after_build:
  - cd ..
  - dir
  - 7z a release.zip build\bin\aseprite.exe
  - 7z a release.zip build\bin\gen.exe
  - 7z a release.zip build\bin\modp_b64_gen.exe
  - 7z a release.zip build\bin\data\
  - cd build
  - cd bin
  - dir
  
artifacts:
  - path: release.zip
    name: release
    type: zip

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "NMake Makefiles" -DENABLE_TESTS=ON -DENABLE_UI=%ENABLE_UI%
  - nmake
  - ctest --output-on-failure
